[project]
name = "sleeper-mcp"
version = "0.1.0"
description = "MCP server for Sleeper fantasy football API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.0.0",
    "httpx>=0.25.0",
    "pydantic>=2.0.0",
    "fastmcp>=0.9.0",
    "typer>=0.16.0",
]
